# Generated by Django 4.1.3 on 2022-11-23 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie", name="name", field=models.CharField(max_length=250),
        ),
    ]
